(() => {
  // UI elements
  const fileInput = document.getElementById('fileInput');
  const profileNameEl = document.getElementById('profileName');
  const quoteCountEl = document.getElementById('quoteCount');
  const startBtn = document.getElementById('startBtn');
  const resetBtn = document.getElementById('resetGame');
  const statementEl = document.getElementById('statement');
  const provenanceEl = document.getElementById('provenance');
  const paraphraseEl = document.getElementById('paraphrase');
  const translationEnglishEl = document.getElementById('translationEnglish');
  const translationPolishEl = document.getElementById('translationPolish');
  const translationGermanEl = document.getElementById('translationGerman');
  const translationEnglishSourceEl = document.getElementById('translationEnglishSource');
  const translationPolishSourceEl = document.getElementById('translationPolishSource');
  const translationGermanSourceEl = document.getElementById('translationGermanSource');
  const translationProvenanceEl = document.getElementById('translationProvenance');
  const realBtn = document.getElementById('realBtn');
  const aiBtn = document.getElementById('aiBtn');
  const roundEl = document.getElementById('currentRound');
  const confettiEl = document.getElementById('confetti');
  const gameSection = document.querySelector('.game');
  const scoreEl = document.getElementById('score');
  const historyList = document.getElementById('historyList');
  const clearHistoryBtn = document.getElementById('clearHistory');
  const generatedSection = document.getElementById('generatedSection');
  const generatedQuotesList = document.getElementById('generatedQuotesList');

  let profile = { name: '—', quotes: [] };
  let profileText = '';
  let game = { items: [], index: 0, score: 0, finished: false };

  function renderProvenance(item){
    if(!provenanceEl || !item){ return; }
    provenanceEl.hidden = false;
    provenanceEl.className = 'provenance ' + (item.type === 'real' ? 'real' : item.source === 'openai' ? 'openai' : 'local');
    const dot = '<span class="dot" aria-hidden="true"></span>';
    if(item.type === 'real'){
      provenanceEl.innerHTML = dot + '<span>Real: from uploaded profile</span>';
    }else if(item.source === 'openai'){
      provenanceEl.innerHTML = dot + '<span>AI provenance: generated by OpenAI API</span>';
    }else{
      provenanceEl.innerHTML = dot + '<span>AI provenance: local fallback logic in app.js</span>';
    }
  }

  function sourceLabel(source){
    return source === 'openai' ? 'OpenAI AI' : source === 'fallback' ? 'local fallback' : 'no translation';
  }

  function renderTranslationProvenance(source, sources, error){
    if(!translationProvenanceEl) return;
    const sourceValues = Object.values(sources || {}).filter(Boolean);
    const hasMixedSources = sourceValues.length > 1 && new Set(sourceValues).size > 1;
    const labels = {
      openai: 'Translations: real AI via OpenAI API',
      fallback: 'Translations: local fallback logic in app.js',
      none: 'Translations: none performed',
      mixed: 'Translations: mixed sources — see each line'
    };
    const kind = hasMixedSources ? 'mixed' : (labels[source] ? source : 'none');
    translationProvenanceEl.hidden = false;
    translationProvenanceEl.className = 'provenance translation-provenance ' + kind;
    const detail = error && kind === 'fallback' ? ` (${error})` : '';
    translationProvenanceEl.innerHTML = '<span class="dot" aria-hidden="true"></span><span>' + labels[kind] + detail + '</span>';

    [[translationEnglishSourceEl, sources && sources.english], [translationPolishSourceEl, sources && sources.polish], [translationGermanSourceEl, sources && sources.german]].forEach(([el, value]) => {
      if(!el) return;
      el.hidden = !hasMixedSources;
      el.textContent = hasMixedSources ? sourceLabel(value) : '';
    });
  }

  function renderTranslations(translations){
    if(translationEnglishEl) translationEnglishEl.textContent = translations.english || '—';
    if(translationPolishEl) translationPolishEl.textContent = translations.polish || '—';
    if(translationGermanEl) translationGermanEl.textContent = translations.german || '—';
  }

  async function translateQuote(text){
    const original = String(text || '').trim();
    if(!original) return { translations: { english: '', polish: '', german: '' }, source: 'none' };
    const endpoints = [`${window.location.origin}/api/translate`];
    // The UI may be opened from a static preview server. Retry the Node API's
    // documented default port so the request reaches the OpenAI-backed route.
    if(window.location.port !== '3000') endpoints.push('http://localhost:3000/api/translate');
    let lastError = 'translation endpoint unavailable';
    for(const endpoint of [...new Set(endpoints)]){
      try{
        const resp = await fetch(endpoint, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ text: original })
        });
        if(resp.ok){
          const result = await resp.json();
          if(result && result.translations && result.translations.english && result.translations.polish && result.translations.german){
            const source = result.source || 'none';
            const sources = result.sources || { english: source, polish: source, german: source };
            console.info('[translation] completed via ' + endpoint, source, sources);
            return { translations: result.translations, source, sources };
          }
          lastError = `invalid translation response from ${endpoint}`;
        }else{
          lastError = `HTTP ${resp.status} from ${endpoint}`;
        }
      }catch(e){ lastError = `${endpoint}: ${e.message}`; }
    }
    console.warn('[translation] API request failed:', lastError);
    return { translations: { english: englishParaphrase(original), polish: original, german: original }, source: 'fallback', sources: { english: 'fallback', polish: 'fallback', german: 'fallback' }, error: lastError };
  }

  function renderGeneratedQuotes(items){
    if(!generatedSection || !generatedQuotesList) return;
    generatedQuotesList.innerHTML = '';
    items.filter(item => item.type === 'ai').forEach((item, index)=>{
      const li = document.createElement('li');
      li.appendChild(document.createTextNode(`${index + 1}. ${item.text}`));
      const source = document.createElement('span');
      source.className = 'generated-source ' + (item.source === 'openai' ? 'openai' : 'local');
      source.textContent = item.source === 'openai' ? 'OpenAI API' : 'local app.js fallback';
      li.appendChild(source);
      generatedQuotesList.appendChild(li);
    });
    generatedSection.hidden = generatedQuotesList.children.length === 0;
  }

  // History stored in localStorage
  function loadHistory(){
    try{ return JSON.parse(localStorage.getItem('dt_history')||'[]') }catch(e){return[]}
  }
  function saveHistory(h){ localStorage.setItem('dt_history', JSON.stringify(h)) }

  function renderHistory(){
    const h = loadHistory();
    historyList.innerHTML = '';
    h.sort((a,b)=>b.score-a.score || b.time - a.time).forEach(entry=>{
      const li = document.createElement('li');
      li.textContent = `${entry.name} — ${entry.score}/10 (${new Date(entry.time).toLocaleString()})`;
      historyList.appendChild(li);
    })
  }

  // Parse uploaded markdown profile
  function parseProfile(mdText){
    // Extract name from top-level header
    let name = '—';
    const nameMatch = mdText.match(/^#\s*Style Profile:\s*(.+)$/im);
    if(nameMatch) name = nameMatch[1].replace(/—.*/,'').trim();

    // Locate the '## Quote pool' section using string search to be robust to line breaks
    const lower = mdText.toLowerCase();
    const header = '## quote pool';
    const startIdx = lower.indexOf(header);
    const quotes = [];
    if(startIdx !== -1){
      // find next header occurrence (\n## ) after startIdx
      let rest = mdText.slice(startIdx);
      // find the position of the next '\n## ' (or CRLF) in rest
      const nextHeaderRel = rest.search(/\r?\n##\s/);
      const block = nextHeaderRel === -1 ? rest : rest.slice(0, nextHeaderRel);
      // remove the first header line
      const blockBody = block.replace(/^[^\n]*\n?/, '');
      const lines = blockBody.split(/\r?\n/);

      // Accumulate numbered items that may span multiple lines
      let current = null;
      for(const raw of lines){
        const line = raw.replace(/\u00A0/g,' ').replace(/\t/g,'    ');
        const m = line.match(/^\s*(\d+)\.\s*(.*)$/);
        if(m){
          // push previous
          if(current){
            const cleaned = extractQuoted(current);
            if(cleaned) quotes.push(cleaned);
          }
          current = m[2] || '';
        } else if(current !== null){
          // continuation line for current numbered item (indented or plain continuation)
          if(line.trim() === '') continue;
          current += ' ' + line.trim();
        }
      }
      // push last
      if(current){
        const cleaned = extractQuoted(current);
        if(cleaned) quotes.push(cleaned);
      }
    }
    return { name, quotes };
  }

  // Extract quoted content if present and normalize only the outer delimiters.
  function cleanQuoteText(value){
    let text = String(value || '').replace(/\s+/g, ' ').trim();
    if(!text) return '';
    const pairs = [['"','"'], ['“','”'], ['„','“'], ['«','»']];
    for(const [open, close] of pairs){
      if(text.startsWith(open) && text.endsWith(close) && text.length >= open.length + close.length){
        text = text.slice(open.length, text.length - close.length).trim();
        break;
      }
    }
    return text;
  }

  function extractQuoted(s){
    const t = String(s || '');
    if(!t) return null;
    const matchers = [/“([\s\S]*?)”/, /„([\s\S]*?)“/, /«([\s\S]*?)»/, /"([\s\S]*?)"/];
    for(const matcher of matchers){
      const match = t.match(matcher);
      if(match) return cleanQuoteText(match[1]);
    }
    return cleanQuoteText(t);
  }

  function enableStartIfReady(){
    startBtn.disabled = profile.quotes.length === 0;
  }

  function shuffle(a){ for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]} }

  // Improved fake generation: combine several lightweight transformations
  function generateFakeFrom(real){
    const r = String(real || '').trim();
    if(!r) return '(no content)';

    const smallSyn = {
      'aber':'but','danke':'thanks','ich':'I','wir':'we','nicht':'not','schnell':'quick','heute':'today'
    };

    function replaceSyn(s){
      return s.split(/(\W+)/).map(tok=>{
        const low = tok.toLowerCase();
        if(smallSyn[low]){
          // preserve capitalization
          if(tok[0] && tok[0] === tok[0].toUpperCase()) return capitalize(smallSyn[low]);
          return smallSyn[low];
        }
        return tok;
      }).join('');
    }

    function capitalize(t){ return t.charAt(0).toUpperCase()+t.slice(1) }

    // strategies
    const strategies = [
      s => 'To be honest, ' + s.replace(/^['"“”]+|['"“”]+$/g,'').replace(/\.$/,'') + '.',
      s => replaceSyn(s).replace(/\b(und|aber|oder)\b/gi, (m)=>', ' + m),
      s => s.split(/[,;:]/).reverse().join(' — ').replace(/\s+/g,' ').trim() + '.',
      s => s.replace(/\b(I am|ich bin)\b/gi,'I\'m').replace(/\bwe\b/gi,'we all'),
      s => s + ' 🤔',
    ];

    // pick a strategy and apply
    const pick = strategies[Math.floor(Math.random()*strategies.length)];
    let out = pick(r);
    // fallback short paraphrase
    if(out === r) out = 'Paraphrase: ' + r;

    // ensure length of at least a few words (avoid one-word or identical short outputs)
    const minWords = 4;
    const wordCount = out.split(/\s+/).filter(Boolean).length;
    if(wordCount < minWords){
      const extras = ['I would prioritise follow-up.', 'Let\'s align on next steps.', 'Short follow-up planned.'];
      out = out + ' ' + extras[Math.floor(Math.random()*extras.length)];
    }

    // randomly add abbreviation sometimes to fit style
    if(Math.random() < 0.12) out = out + ' FYI.';

    return out;
  }

  // Basic German->English paraphrase for demonstration only (small dictionary)
  function englishParaphrase(text){
    if(!text) return '';
    // Phrase-first mapping (longer phrases first)
    const phraseMap = [
      ['alles gut','all good'],
      ['danke dir dafür','thanks for that'],
      ['danke dir','thanks'],
      ['wie erwartet','as expected'],
      ['gar kein Thema','no problem at all'],
      ['kannst du','can you'],
      ['soll ich','should I'],
      ['wenn möglich','if possible'],
      ['mal kurz','briefly'],
    ];
    const wordMap = {
      'aber':'but','ich':'I','wir':'we','nicht':'not','schnell':'quick','heute':'today','fyi':'FYI','rolle':'role','thematik':'issue','feedback':'feedback'
    };

    let s = text;
    // apply phrase replacements first
    phraseMap.forEach(([k,v])=>{
      const re = new RegExp('\\b'+escapeReg(k)+'\\b','ig');
      s = s.replace(re, v);
    });
    // then word replacements
    Object.keys(wordMap).forEach(k=>{
      const re = new RegExp('\\b'+escapeReg(k)+'\\b','ig');
      s = s.replace(re, wordMap[k]);
    });

    // If still contains typical German words, try to remove or translate a few common ones
    const commonGerman = [' und ', ' aber ', ' das ', ' die ', ' der ', 'zu ', 'dass', 'schau', 'passt'];
    commonGerman.forEach(g=>{
      if(new RegExp(escapeReg(g),'i').test(s)) s = s.replace(new RegExp(escapeReg(g),'ig'), ' ');
    });

    // Clean up spacing and punctuation
    s = s.replace(/\s+/g,' ').trim();
    if(!/[\.\?\!]$/.test(s)) s = s + '.';
    return '(EN) ' + s;
  }

  function escapeReg(s){ return s.replace(/[.*+?^${}()|[\]\\]/g,'\\$&') }

  async function buildGame(){
    const pool = profile.quotes.slice();
    // ensure at least 2 real and 2 ai
    const minReal = 2, minAi = 2;
    const desiredReal = Math.min(8, Math.max(minReal, Math.floor(Math.random()*7)+minReal));
    // realCount can't exceed available quotes and must leave at least minAi ai slots
    const realCount = Math.min(desiredReal, Math.max(minReal, Math.min(pool.length, 10 - minAi)));
    const aiCount = 10 - realCount;

    const items = [];
    const seen = new Set();
      // If server is available and user provided quotes, try to request better AI-generated quotes
      let serverAIs = [];
      let aiSource = 'local';
      try{
        if(window.fetch && pool.length){
          const resp = await fetch('/api/generate', {
            method:'POST',
            headers:{'Content-Type':'application/json'},
            body: JSON.stringify({
              quotes: pool,
              aiCount: 10,
              profileName: profile.name,
              profileText: profileText
            })
          });
          if(resp.ok){
            const json = await resp.json();
            if(json && json.source === 'openai' && Array.isArray(json.ai)){
              aiSource = 'openai';
              serverAIs = json.ai.map(cleanQuoteText).filter(Boolean).slice(0, 10);
            }
          }
        }
      }catch(e){ console.warn('AI generate failed', e.message); }
    const norm = s => String(s||'').replace(/\s+/g,' ').trim().toLowerCase();

    // choose unique real quotes
    const available = pool.slice();
    for(let i=0;i<realCount && available.length>0;i++){
      const idx = Math.floor(Math.random()*available.length);
      const pick = available.splice(idx,1)[0];
      items.push({text: pick, type: 'real'});
      seen.add(norm(pick));
    }

    // First use LLM-generated AI quotes as the real AI pool.
    // This keeps real uploaded quotes and AI-generated quotes distinctly separated by source/type.
    while(items.filter(it=>it.type==='ai').length < aiCount && serverAIs.length > 0){
      const fake = serverAIs.shift();
      const n = norm(fake);
      if(fake && !seen.has(n)){
        items.push({text: fake, type: 'ai', source: aiSource});
        seen.add(n);
      }
    }

    // generate unique AI items until we reach aiCount
    let aiAttempts = 0;
    let guard = 0;
    while(items.filter(it=>it.type==='ai').length < aiCount && guard < 500){
      guard++;
      const srcs = [];
      if(profile.quotes.length) srcs.push(profile.quotes[Math.floor(Math.random()*profile.quotes.length)]);
      if(profile.quotes.length > 1 && Math.random() < 0.8) {
        let s2 = profile.quotes[Math.floor(Math.random()*profile.quotes.length)];
        let tries=0; while(s2===srcs[0] && tries<6){ s2 = profile.quotes[Math.floor(Math.random()*profile.quotes.length)]; tries++; }
        if(s2) srcs.push(s2);
      }
      const combined = srcs.length>1 ? (srcs.map(x=>String(x).replace(/^"|"$/g,'')).join(' — ')) : (srcs[0]||'Working in small steps');
      let fake = generateFakeFrom(combined);
      if(fake.split(/\s+/).filter(Boolean).length < 5) fake = fake + ' Please let me know the next steps.';
      const n = norm(fake);
      if(!seen.has(n)){
        items.push({text: fake, type: 'ai', source: 'local'});
        seen.add(n);
      } else {
        aiAttempts++;
        let fallback = '';
        if(serverAIs.length){ fallback = serverAIs.shift(); }
        if(!fallback) fallback = generateFakeFrom(combined);
        if(aiAttempts > 20){
          fallback = fallback + ' ✨' + Math.floor(Math.random()*900+100);
          const nn = norm(fallback);
          if(!seen.has(nn)){ items.push({text: fallback, type:'ai', source: 'local'}); seen.add(nn); }
        }
      }
    }

    // if we still don't have 10 items (rare), fill with short generated variants
    let fillGuard = 0;
    while(items.length < 10 && fillGuard < 50){
      fillGuard++;
      const src = profile.quotes.length ? profile.quotes[Math.floor(Math.random()*profile.quotes.length)] : 'Working in small steps';
      let fake = generateFakeFrom(src) + ' ⚡';
      const n = norm(fake);
      if(!seen.has(n)){ items.push({text: fake, type:'ai', source:'local'}); seen.add(n); }
    }

    // finally shuffle
    shuffle(items);
    game.items = items; game.index = 0; game.score = 0; game.finished = false;
    renderGeneratedQuotes(items);
    roundEl.textContent = '0'; scoreEl.textContent = '0';
    statementEl.textContent = 'Press Real or AI to guess the first statement.';
    renderTranslations({ english: '—', polish: '—', german: '—' });
    if(translationProvenanceEl) translationProvenanceEl.hidden = true;
    if(provenanceEl) provenanceEl.hidden = true;
  }

  function ensureUniqueItems(items){
    const seen = new Set();
    // normalize helper
    const norm = s => String(s||'').replace(/\s+/g,' ').trim().toLowerCase();
    // iterate and ensure uniqueness; for AI entries, attempt multiple regenerations
    for(let i=0;i<items.length;i++){
      let text = items[i].text;
      let attempts = 0;
      while(seen.has(norm(text)) && attempts < 12){
        if(items[i].type === 'ai'){
          // pick two different sources to generate a new fake
          let a = profile.quotes.length ? profile.quotes[Math.floor(Math.random()*profile.quotes.length)] : '';
          let b = profile.quotes.length ? profile.quotes[Math.floor(Math.random()*profile.quotes.length)] : '';
          let tries = 0;
          while(b === a && tries < 8 && profile.quotes.length>1){ b = profile.quotes[Math.floor(Math.random()*profile.quotes.length)]; tries++ }
          const combined = a && b && a !== b ? (a.replace(/^"|"$/g,'') + ' — ' + b.replace(/^"|"$/g,'')) : (a||b||'Working in small steps');
          text = generateFakeFrom(combined);
          // A duplicate is regenerated by the local app.js logic, regardless
          // of where the original duplicate came from.
          items[i].source = 'local';
          // add playful suffix sometimes
          if(Math.random() < 0.25) text = text + ' ✨';
        } else {
          // real entries should not be modified; if duplicate (unlikely), append short token
          text = items[i].text + ' (dup)';
        }
        attempts++;
      }
      if(seen.has(norm(text))){
        // last-resort uniqueifier
        text = items[i].text + ' #' + Math.floor(Math.random()*9000+1000);
      }
      items[i].text = text;
      seen.add(norm(text));
    }
  }

  function showNext(){
    if(game.index >= game.items.length){
      endGame(); return;
    }
    const item = game.items[game.index];
    statementEl.textContent = '';
    renderTranslations({ english: '—', polish: '—', german: '—' });
    // reveal animation
    roundEl.textContent = String(game.index + 1);
    statementEl.classList.remove('pop');
    // small type-in reveal
    let i = 0, txt = String(item.text || '');
    const step = () => {
      if (i < txt.length) {
        i = Math.min(i + 3, txt.length);
        statementEl.textContent = txt.slice(0, i);
        requestAnimationFrame(step);
      } else {
        // Always commit the complete string on the terminal frame. This
        // prevents the reveal animation from ever leaving a truncated quote.
        statementEl.textContent = txt;
        statementEl.classList.add('pop');
        translateQuote(txt).then(result => {
          renderTranslations(result.translations);
          renderTranslationProvenance(result.source, result.sources, result.error);
        });
        renderProvenance(item);
      }
    };
    requestAnimationFrame(step);
  }

      // Visual feedback for guess result
      function showFeedback(correct){
        // create pill
        let holder = gameSection.querySelector('.feedback');
        if(!holder){ holder = document.createElement('div'); holder.className='feedback'; gameSection.appendChild(holder); }
        holder.innerHTML = '';
        const pill = document.createElement('div'); pill.className = 'pill ' + (correct? 'correct':'wrong');
        pill.textContent = correct? '✔ Correct!':'✖ Wrong!';
        holder.appendChild(pill);
        // trigger show
        requestAnimationFrame(()=> pill.classList.add('show'));
        // confetti on correct
        if(correct && confettiEl){
          for(let i=0;i<18;i++){
            const d = document.createElement('div'); d.className='dot'; d.style.left = (10 + Math.random()*80) + '%'; d.style.background = ['#ff3b3b','#ffd34d','#4ce0a8','#7ad8ff','#d68bff'][Math.floor(Math.random()*5)];
            confettiEl.appendChild(d);
            // animate in
            setTimeout(()=> d.classList.add('show'), 20 + Math.random()*200);
            // cleanup
            setTimeout(()=> d.remove(), 1400);
          }
        }
        // remove pill after delay
        setTimeout(()=>{ if(pill) pill.classList.remove('show'); }, 1000);
      }

  function endGame(){
    game.finished = true;
    statementEl.textContent = `Round complete — final score ${game.score}/10`;
    // save to history
    const h = loadHistory();
    h.push({ name: profile.name||'—', score: game.score, time: Date.now() });
    saveHistory(h);
    renderHistory();
  }

  // UI handlers
  fileInput.addEventListener('change', async (ev)=>{
    const f = ev.target.files && ev.target.files[0];
    if(!f) return;
    const text = await f.text();
    profileText = text;
    const parsed = parseProfile(text);
    // if there is a finished game and different profile, keep history already saved on end
    profile = parsed;
    profileNameEl.textContent = profile.name || '—';
    quoteCountEl.textContent = profile.quotes.length;
    enableStartIfReady();
    // populate test section with parsed quotes
    try{
      const list = document.getElementById('parsedQuotesList');
      list.innerHTML = '';
      profile.quotes.forEach((q,i)=>{
        const li = document.createElement('li');
        li.textContent = `${i+1}. ${q}`;
        list.appendChild(li);
      });
      document.getElementById('testSection').style.display = profile.quotes.length? 'block':'none';
    }catch(e){/* ignore in non-browser tests */}
  });

  // hide test section
  const hideTestBtn = document.getElementById('hideTest');
  if(hideTestBtn){ hideTestBtn.addEventListener('click', ()=>{ document.getElementById('testSection').style.display='none'; }); }

  startBtn.addEventListener('click', async ()=>{
    startBtn.disabled = true;
    await buildGame();
    showNext();
  });

  realBtn.addEventListener('click', ()=>{ handleGuess('real') });
  aiBtn.addEventListener('click', ()=>{ handleGuess('ai') });

  function handleGuess(guess){
    if(game.finished || !game.items.length) return;
    const cur = game.items[game.index];
    const correct = guess === cur.type;
    if(correct) game.score += 1;
    game.index += 1;
    scoreEl.textContent = String(game.score);
    // show animated feedback
    showFeedback(correct);
    if(game.index >= game.items.length) setTimeout(()=> endGame(), 700); else setTimeout(()=> showNext(), 700);
  }

  resetBtn.addEventListener('click', ()=>{
    profile = { name: '—', quotes: [] };
    profileText = '';
    game = { items: [], index: 0, score: 0, finished: false };
    profileNameEl.textContent = '—'; quoteCountEl.textContent = '0'; startBtn.disabled = true;
    statementEl.textContent = 'Upload profile and press Start.'; scoreEl.textContent='0'; roundEl.textContent='0';
    renderTranslations({ english: '—', polish: '—', german: '—' });
    if(provenanceEl) provenanceEl.hidden = true;
    if(translationProvenanceEl) translationProvenanceEl.hidden = true;
    const list = document.getElementById('parsedQuotesList'); if(list) list.innerHTML = '';
    if(generatedQuotesList) generatedQuotesList.innerHTML = '';
    if(generatedSection) generatedSection.hidden = true;
  });

  clearHistoryBtn.addEventListener('click', ()=>{ if(confirm('Clear history?')){ saveHistory([]); renderHistory(); } });

  // init
  renderHistory();
  // Show start when quotes present
  fileInput.addEventListener('change', ()=>{ startBtn.disabled = profile.quotes.length===0 });

  // Enable start when a profile is already loaded via drag/drop
  startBtn.disabled = true;
  // expose for debugging
  window.DT = { profile, game };
})();
